projects:
  storytails:
    schemaPath: src/graphql/schema.json
    includes:
      - StoryApi
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
